### ISSUE TITLE
I found that the dataset is not available when I clicked on the link

### ISSUE THREAD

**Issue by jiangyijin** [feiyang-cai/osr_vit#3]
Hello, I found that the dataset is not available when I clicked on the link. Could you please provide me with the download link for the dataset again? Or could you tell me the format of the dataset?

**Comment by feiyang-cai** [comment]
The link could not be maintained by others anymore... 

The TinyImageNet is the standard dataset, you might found it here, https://paperswithcode.com/dataset/tiny-imagenet.

**Comment by jiangyijin** [comment]
Thank you. And when I run the measure_osrdetector.py, there's an error called 'KeyError: 'classes_mean'' when loading the ckpt. I'm wondering what's the meaning of the ckpt key  'classes_mean' and how can I get it.

In def main():
classes_mean = ckpt['classes_mean']
Traceback (most recent call last):
  File "/snap/pycharm-community/425/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
KeyError: 'classes_mean'


> The link could not be maintained by others anymore...
> 
> The TinyImageNet is the standard dataset, you might found it here, https://paperswithcode.com/dataset/tiny-imagenet.
